### ISSUE TITLE
Compartir en la página

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DerechosDeEstudiantes-2#55]
Pensar cómo y ver si se puede WhatsApp

**Comment by Vitoartois** [comment]
Las noticias que aparecen en el inicio de montevideo.gub.uy tienen la opción de compartir por WhatsApp, capaz te sirve investigar eso.

**Comment by fernandouval** [comment]
Esto quedó, pero lo que mostraban los buscadores es que no estamos compartinedo redes de las organizaciones (nosotros), no sé si tiene sentido, creo que si y asumo que es algo que vamos a poner en el footer general, capaz vale la pena ponerlo ya en los proyectos que editemos...

**Comment by danielcarranza** [comment]
Igual creo que cerraría el issue. Cuando tengamos footer, crearemos el de agregarlo, ¿no?
