### ISSUE TITLE
Al editar una respuesta, se cambia la pregunta a la que está asociada en el editor.

### ISSUE THREAD

**Issue by danielcarranza** [datauy/DerechosDeEstudiantes-2#83]
Una respuesta asociada a una pregunta X, al entrar al editor "olvida" esa asociación y en el campo de pregunta asociada aparece la primera de la lista.

Video: https://www.dropbox.com/transfer/AAAAABsS7RlQfbds8EKjoOAKLUM4bNU7gswZdkckG_hiJ3G0GaaWGMg

**Comment by fernandouval** [comment]
No me pasa @danielcarranza :
![image](https://user-images.githubusercontent.com/1556819/76921837-c8758f80-68ad-11ea-8a44-73dd65302eb3.png)

**Comment by danielcarranza** [comment]
Anda a editar una respuesta desde "Respuestas" no a crear una nueva

**Comment by danielcarranza** [comment]
Está par cerrar, ¿no @fernandouval?
