### ISSUE TITLE
Issue de evaluación técnica

### ISSUE THREAD

**Issue by JenniferHuertas** [datauy/DerechosDeEstudiantes-2#95]
## Este issue forma parte de un proceso de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID. @ChayoVS.

Al haber contrastado la información presentada en el repo oficial hemos encontrado los siguientes puntos a mejorar:
- [x] Agregar el microservicio de reportes de evaluación estática de código de Sonarcloud <https://sonarcloud.io/>
- [x] Agregar el badge de este servicio visible en el readme.md
- [ ] Generar reportes de calidad de código

**Comment by danielcarranza** [comment]
[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?project=datauy_DerechosDeEstudiantes-2&metric=alert_status)](https://sonarcloud.io/dashboard?id=datauy_DerechosDeEstudiantes-2)

**Comment by knlopenknowledge** [comment]
Hola @danielcarranza muchas gracias por todo el trabajo en la piloto, estoy revisando que para pasar a publicar esta herramienta en code.iadb.org estaría faltando agregar el badge de Quality gate passed de Sonarcloud que generaste en el readme.md. Con esto, los puntos que levantó @JenniferHuertas quedarían cerrados. Quedamos super atentos a cualquier duda o consulta para poder cerrar este issue de evaluación técnica.

**Comment by danielcarranza** [comment]
@knlopenknowledge ¡Listo!
