### ISSUE TITLE
Issue de licenciamiento

### ISSUE THREAD

**Issue by JenniferHuertas** [datauy/DerechosDeEstudiantes-2#96]
## Este issue forma parte de un procesos de revisión de la piloto @BID-COMUNIDADES/laboratoria-code-squads de la iniciativa Código para el desarrollo de @EL-BID.

- [x] La herramienta no cuenta con licencia open source. Sugerimos revisar la web <https://choosealicense.com/>

**Comment by danielcarranza** [comment]
Quedó agregado LICENSE.md
